### Összes sportoló
GET http://localhost:8080/athletes

### Új sportoló
POST http://localhost:8080/athletes
Content-Type: application/json

{
  "name": "Teszt Sportoló",
  "birthDate": "2003-05-12",
  "gender": "MALE"
}


### törlés
DELETE http://localhost:8080/athletes/1
Content-Type: application/json


### update

PUT http://localhost:8080/athletes/2
Content-Type: application/json

{
  "name": "Módosított Sportoló",
  "birthDate": "2003-05-12",
  "gender": "MALE"
}

### Összes vérvizsgálat
GET http://localhost:8080/bloodtests


### BloodTest létrehozása
POST http://localhost:8080/bloodtests
Content-Type: application/json

{
  "athlete": {
    "id": 3
  },
  "date": "2026-09-07",
  "laboratoryName": "Teszt Labor"
}


### Marker létrehozása
POST http://localhost:8080/markers
Content-Type: application/json

{
  "name": "Hemoglobin",
  "unit": "g/L"
}

### MarkerValue létrehozása
POST http://localhost:8080/markervalues
Content-Type: application/json

{
  "bloodTest": {
    "id": 1
  },
  "marker": {
    "id": 1
  },
  "value": 145.0
}


### Összes MarkerValue
GET http://localhost:8080/markervalues

### Test import
POST http://localhost:8080/import/excel
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Thesis_project.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< C:\Users\gergu\IdeaProjects\szakdolgozat\src\main\resources\Thesis_project.xlsx
--WebAppBoundary--


### Marker elemzés - Hemoglobin
GET http://localhost:8080/analysis/athlete/34/marker/1?sampleType=BLOOD

### Marker elemzés - dátum
GET http://localhost:8080/analysis/athlete/34/date/2022-11-09

### Marker elemzés - corelation
GET http://localhost:8080/analysis/athlete/34/correlation?marker1Id=1&marker2Id=4&sampleType=BLOOD

### Marker elemzés - markerpárok
GET http://localhost:8080/analysis/athlete/35/correlations?sampleType=BLOOD

### quality check
GET http://localhost:8080/analysis/athlete/35/data-quality

### ML test
GET http://localhost:8080/analysis/athlete/35/ml-data

### anomaly test
GET http://localhost:8080/analysis/athlete/37/anomalies

### hibás sportoló test
GET http://localhost:8080/analysis/athlete/99999/anomalies
### marker test
GET http://localhost:8080/analysis/athlete/35/markers